version: "3"
services:
  uwsgi:
    build: .
    container_name: sti_uwsgi
    restart: always
    ports:
      - 12321:9090
    environment:
      FLASK_APP: messenger
      STI_MSN_DB: mysql+pymysql://sti:stipass@sti_db/sti
    depends_on:
      - db

  db:
    build: docker/mariadb
    container_name: sti_db
    restart: always
    ports:
      - 32123:3306
    environment:
      MYSQL_USER: sti
      MYSQL_ROOT_PASSWORD: stipass
      MYSQL_PASSWORD: stipass
      MYSQL_DATABASE: sti

  adminer:
    image: adminer
    container_name: sti_adminer
    restart: always
    ports:
      - 45654:8080
    environment:
      ADMINER_DEFAULT_SERVER: sti_db
    depends_on:
      - db
