name: Build & publish stable Docker image

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: |
            ${{ runner.os }}-pip

      - uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true

      - uses: actions/setup-python@v2
        with:
            python-version: '3.8.6'

      - name: Build application Docker image
        run: |
          echo ${{ secrets.token }} | docker login -u serphentas --password-stdin
          docker build -t serphentas/sti-project-1-app .
          docker push serphentas/sti-project-1-app

      - name: Build database Docker image
        run: |
          cd docker/mariadb
          echo ${{ secrets.token }} | docker login -u serphentas --password-stdin
          docker build -t serphentas/sti-project-1-db .
          docker push serphentas/sti-project-1-db
